### ISSUE TITLE
limits file passed without directory, fails

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/limitador#119]
There is a bug in the way we resolve the directory to watch for changes on the limits file.
If you start limitador-server with a "local to the dir" limits file, the server panics:

```
./target/debug/limitador-server test.yaml
Limitador Server v1.0.0-dev (edddfbce-dirty)  debug build
Error: Error { kind: PathNotFound, paths: [""] }
```

This is because of how we extract the parent directory: `Path::new(&limit_file).parent().unwrap()` where parent is now `""`
We need to resolve the absolute path before doing this…

**Comment by eguzki** [comment]
This must be some edge case where depending on the underlying OS, the watcher will work in one way or another. 

First, in linux, it works. I have tested with current [main](https://github.com/Kuadrant/limitador/commit/56bdb3dc53d523efa6b9bb67413b949512a10ea2)

<details>

```
cat <<EOF >limits.yaml
---
- namespace: test_namespace
  max_value: 20
  seconds: 60
  conditions:
    - "req.method == 'POST'"
  variables:
    - user_id
EOF
```
```
target/debug/imitador-server limits.yaml
```

```yaml
curl http://127.0.0.1:8080/limits/test_namespace 2>/dev/null | yq e -P
- namespace: test_namespace
  max_value: 20
  seconds: 60
  name: null
  conditions:
    - req.method == 'POST'
  variables:
    - user_id
```

</details>


The expression `Path::new(&limit_file).parent().unwrap()` results in empty path `""` and when passed to the watcher, the watcher fires events when fthe file content changes.  

What I would do is to replace the empty path with `"."` (when the path is empty, obviously). Then watch on `"."` as in the example shown in the [doc](https://docs.rs/notify/latest/notify/#examples)

```rust
// it should not fail because the limits file has already been read
let mut limits_file_dir = Path::new(&limit_file).parent().unwrap();
if limits_file_dir.as_os_str().is_empty() {                        
⦙   limits_file_dir = Path::new(".");                              
}                                                                  
```

wdyt @alexsnaps ?
