### ISSUE TITLE
Get `enable_x_ratelimit_headers: DRAFT_VERSION_03` to work

### ISSUE THREAD

**Issue by chirino** [Kuadrant/limitador#156]
I tried setting the [enable_x_ratelimit_headers](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-field-extensions-filters-http-ratelimit-v3-ratelimit-enable-x-ratelimit-headers) option in the envoy rate limiting filter.  But the expected headers were not set in the response.

the filter's configuration looks like: 
```
                  - name: envoy.filters.http.ratelimit
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                      domain: nexodus
                      failure_mode_deny: false
                      timeout: 0.05s
                      enable_x_ratelimit_headers: DRAFT_VERSION_03
                      rate_limit_service:
                        transport_api_version: V3
                        grpc_service:
                          envoy_grpc:
                            cluster_name: ratelimiter
```

The only header I see in the responses is `x-envoy-ratelimited: true`, I was hoping to get headers like `X-RateLimit-Limit: 10, 10;w=1;name="per-ip", 1000;w=3600`

 ## Tasks

 - [x] Add support in Limitador's gRPC
 - [x] Add configuration option to Limitador server
 - [x] Add support in the wasm-shim
 - [x] [Add support to configure in limitador-operator](https://github.com/Kuadrant/limitador-operator/pull/66)
