### ISSUE TITLE
Request with `|` (pipe) character in authority header is auto-rejected by Limitador

### ISSUE THREAD

**Issue by rahulanand16nov** [Kuadrant/limitador#53]
This issue describes the finding of auto-rejection of requests that contains the pipe character in their `:authority` header field. I tracked down this problem to a dependency named [h2](https://github.com/hyperium/h2).

Following was from the trace logs:
```
malformed headers: malformed authority (b"outbound|8081||limitador.rahul-test.svc.cluster.local"): invalid uri character
```

**Why there is a pipe character in the authority header?** 
That format should be familiar if you have seen Istio's cluster config. Still, if not, that format is auto-generated by Istio's control plane by looking at its service registry.  So, when you add a Limitador service in the cluster where Istio is also present, the service registry picks up the service and sends that to all the Envoys present in the cluster (gateway or sidecar) as a [cluster](https://www.envoyproxy.io/docs/envoy/latest/api-v3/clusters/clusters). And the name of that cluster is of that format as seen above in the log.

As Limitador is used right now, it receives a callout request from an [Envoy's RateLimit filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter) and one particular behavior of envoy is to use the cluster name as `:authority` header of the callout. Hence why you get the pipe character in the header.

**Potential way to solve this problem?**
I have seen a few comments around updating dependencies but I cannot find them right now. One option is to update the dependency which is already a bit old.

Second, I am going to create an issue in the Istio and Envoy repo to highlight this behavior to them. Possibly Istio can change the cluster format or Envoy can allow overriding authority?

cc @maleck13 @unleashed

**Comment by unleashed** [comment]
@rahulanand16nov I don't think it is feasible for Istio to change the cluster name format at this stage - it's been well documented for a long time. It might be easier to change Envoy to use the actual authority rather than the cluster name, but still difficult given how this has been around for long - so failing the above, we'll have to work around this case on our side.

**Comment by rahulanand16nov** [comment]
Good point :thinking: 

I'll add steps to reproduce for anyone picking this up before I get to it.

**Comment by rahulanand16nov** [comment]
cc @alexsnaps

**Comment by rahulanand16nov** [comment]
I have tried using a `DestinationRule` which adds the TLS context to the cluster entry with `SNI`. Envoy swaps the authority header with SNI if present but limitador now rejects the request with a different error: `connection error: http2 error: protocol error: unspecific protocol error detected`

DestinationRule used:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: limitador
  namespace: kuadrant-system
spec:
  host: limitador.kuadrant-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8081
      tls:
        mode: SIMPLE
        sni: rate-limit-cluster
```
