### ISSUE TITLE
all the descriptors are consolidated in a single descriptor

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/limitador#62]
For the following Envoy's RLS request:

```yaml
domain: example.org    
descriptors:           
  - entries:           
    - C: VALUE         
  - entries:           
    - A: VALUE         
    - B: VALUE         
```

the following ratelimit config would be activated and it should not.
```yaml
conditions: []  
max_value: 1                      
seconds: 60                       
variables: ["A", "B", "C"]             
namespace: example.org            
```
