### ISSUE TITLE
Redefine authority of `Limit`s

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/limitador#74]
Currently `Limit`s are "owned" by Limitador. It gets them from a file and then the set of `Limit` can be altered using the REST end points. In a k8s world, that file is a mounted `ConfigMap` and the end-point is invoked based on the changes made to the Custom Resources, i.e. `RateLimitPolicy`'ies. All these `Limit`s are persisted into Redis, when Limitador is configured to use it. 

The problem with this approach is that we end up with two authorities over `Limit`s, that all have a different lifecycle. e.g. Limitador is up & running, loaded an initial set of `Limit`s from the `ConfigMap` as it was when it started. If that `ConfigMap` is changed, Limitador will only pick up those changes when restarted. In the meantime, some `RateLimitPolicy`'ies are being added and the operator changes the config using the REST endpoints on Limitador. For some reason Limitador is down and gets restarted. Currently, only the `Limit`s from the (whatever state it is in) `ConfigMap` are being kept. So for the `Counter`s associated with them. All the other `Limit`s are discarded. 

### Fixing this

While we could "simply" make the operator smarter and "work around" these shortcomings, some of us believe that clearly defining a _single authoritative source_ for the `Limit`s would make the system simpler to manage. After discussing this with @eguzki , we thought a forward would be to _not_ persist `Limit`s in Redis anymore but to only keep them in-memory. They'd be loaded from a single config file from "disk" at start up, and changes to that file would be picked up by Limitador without the need for a restart. In a k8s world, the control plane would be responsible for updating that file accordingly, based of changes to Custom Resources and other `ConfigMap` it'd care about. That way the lifecycle of the different components (the k8s cluster(s), Limitador & Redis) become decoupled & changes are applied consistently.

#### A word on sharding

Interestingly this comes with an additional advantage. If we need to shard the workload across multiple Limitador instances, how that sharding happens is now entirely controlled by the control plane: how to configure Limitador instances and how gateway(s) get to query those. 

### Todo

- [x] #78 
- [x] Load the Limit from the file at start up (and not reconcile with the on-disk state, as they'd be none)
- [x] #79 
- [x] Kuadrant/limitador-operator#21

**Comment by rahulanand16nov** [comment]
Just to clarify, if the operator is down and comes back then it will need to reconcile the current state of the `RateLimits` with the current state of `ConfigMap` instead of sending new limits via an HTTP endpoint.

**Comment by didierofrivia** [comment]
So the state will be always stored in a `ConfigMap`, giving it the authority over the local file in _Limitador_, right? If that's the case, the "real" state of the _Limitador_ instance is irrelevant when resides within k8s which IMHO makes sense in this particular case... either way we'd need to sync both sides which might be a bit of a PITA.

**Comment by eguzki** [comment]
> So the state will be always stored in a ConfigMap, giving it the authority over the local file in Limitador, right?
The configmap is the k8s mechanism to provision the local file in limitador's pod. The authority of the limits belong to the RateLimitPolicies. 

> If that's the case, the "real" state of the Limitador instance is irrelevant when resides within k8s which IMHO makes sense in this particular case... the other way we'd need to sync both sides which might be a bit of a PITA.

I think this is answered. There is no need to sync both sides. The control plane just makes sure that limitador gets the assigned limits and the source of truth lives in the RateLimitPolicies. If the ratelimitpolicies changes, the control plane will reconcile and update accordingly the config map of limitador's pod.

**Comment by eguzki** [comment]
Let me drop here two ideas related to the authority of the limits:

Source of the config map
-----------------
Currently the limitador operator reads RateLimit CRs and reconciles with limitador using the HTTP endpoint. 
I would get rid of the RateLimit CRs. The limits are configured at the Limitador CR. For example:

```yaml
---                                                       
apiVersion: limitador.kuadrant.io/v1alpha1                
kind: Limitador                                           
metadata:                                                 
  name: limitador                                         
spec:                                                     
  replicas: 1                                             
  version: "0.4.0"     
  limits:
  - conditions: ["get-toy == yes"]
    max_value: 2
    namespace: toystore-app
    seconds: 30
    variables: []
  - conditions:
    - "admin == yes"
    max_value: 2
    namespace: toystore-app
    seconds: 30
    variables: []
  - conditions: ["vhaction == yes"]
    max_value: 6
    namespace: toystore-app
    seconds: 30
    variables: []                                                                                        
```

the limitador operator would be responsible of reconciling the content of `spec.limits` with the content config map mounted in the limitador's pod.

Who sets Limitador CR's `spec.limits`? The one reading the RateLimitPolicy CR's: the kuadrant controll plane (kuadrant-controller). The kuadrant control plane is who assigns limits to limitador deployments. The control plane can assign different limit sets to different limitador deployments. Then each limitador deployment may have N replicas, and those N replicas will get the same limit configuration as it belongs to the Limit CR. 

Rate limit counter TYPE
--------------------
Now all the counters are treated equally, they all live in the defined storage. This can be memory, redis or infinispan. 

Since we have decoupled limits from counters, we may decide upon the counter storage type. As counters for 1 sec time period does not seem reasonable to be persisted or even replicated, why not have them in memory regardless of the other counters? So I propose a new attribute of the limit to decide on the counter's storage type. By default it would be the defined storage (memory, redis, infinispan). But you could specify that you want it `in-memory`.  The limit definition would be:
```yaml
  - conditions: ["vhaction == yes"]
    max_value: 6
    namespace: toystore-app
    seconds: 30
    variables: []  
    type: in-memory      
```

wdyt? It is ok to say: it does not make any sense :)
